# Generated by Django 4.0.5 on 2022-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(default=0)),
                ('blood_group', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('verification_code', models.CharField(max_length=8)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(null=0)),
                ('updated_at', models.DateField(null=True)),
                ('removed_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.BigIntegerField(max_length=20)),
                ('diet_title', models.CharField(max_length=100)),
                ('diet_plan', models.TextField(max_length=500)),
                ('diet_duration', models.CharField(max_length=200)),
                ('medicine_details', models.TextField(max_length=500)),
                ('remarks', models.TextField(max_length=500)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateField(null=0)),
                ('updated_at', models.DateField(null=True)),
                ('removed_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'app_diet',
            },
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(max_length=20)),
                ('health_issue', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateField(null=0)),
                ('updated_at', models.DateField(null=True)),
                ('removed_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'app_health_status',
            },
        ),
    ]
